name: Parser Check

on:
  push:
    branches:
      - "**"
      - "master"
  schedule:
    - cron: "0 */2 * * *"

jobs:
  parser_check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Verify comment text parser
        working-directory: ./scripts/lib
        run: |
          ls
          dart pub get
          dart parser_verifier.dart -t ${{ secrets.GITHUB_TOKEN }}