name: Parser Check

on:
  push:
    branches:
      - "**"
      - '!master'

jobs:
  parser_check:
    name: Check comment parser
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      issues: write
    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: submodules/flutter/bin/flutter doctor
      - run: submodules/flutter/bin/flutter pub get
      - run: submodules/flutter/bin/dart scripts/parser_verifier.dart -t ${{ secrets.GITHUB_TOKEN }}